#!/bin/bash

# use first argument as the cell identifier
cell_id=$1

# ensure presence directory for storing products of cell execution
products_dir=${REPRO_DEMO_OUT_DIRNAME}
mkdir -p ${products_dir}

# create a directory for storing temporary files associated with cell execution
if [[ -n REPRO_DEMO_TMP_DIRNAME ]] ; then
    tmp_dir=${REPRO_DEMO_TMP_DIRNAME}
    mkdir -p ${tmp_dir}
else
    tmp_dir=$(mktemp --tmpdir=/tmp -d bash_dev_XXXXXXX)
fi

# name the temporary files for the cell script and its stdout
cell_script=${tmp_dir}/${cell_id}.sh
cell_stdout=${tmp_dir}/${cell_id}.txt

# copy stdin to the cell script file
cat /dev/null > "${cell_script}"
IFS=''; while read line
do
    echo "$line" >> "${cell_script}"
done

# execute the script and save its output
bash "${cell_script}" > ${cell_stdout}

# print the script and any text it wrote to stdout
echo "=========================================== BASH CELL | ${cell_id} ============================================"
cat "${cell_script}"
echo "--------------------------------------------- OUTPUTS -------------------------------------------------"
cat ${cell_stdout}
echo "-------------------------------------------------------------------------------------------------------"
echo
echo
